module.exports = {
  grades: [ // from easiest to most difficult
    {id: 0, name: 'Non coté',           color: '#BDBDBD', points: 0},
    {id: 1, name: 'Novice',             color: '#FFEB3B', points: 1},
    {id: 2, name: 'Débutant',           color: '#FF9800', points: 2},
    {id: 3, name: 'Début de Performant',color: '#8BC34A', points: 3},
    {id: 4, name: 'Performant',         color: '#4CAF50', points: 4},
    {id: 5, name: 'Performant confirmé',color: '#009688', points: 6},
    {id: 6, name: 'Confirmé',           color: '#2196F3', points: 8},
    {id: 7, name: 'Confirmé expert',    color: '#9C27B0', points: 12},
    {id: 8, name: 'Expert',             color: '#f44336', points: 16},
    {id: 9, name: 'Maître',             color: '#FFFFFF', points: 32},
    {id:10, name: 'Mutant',             color: '#263238', points: 64},
  ],
  
  walls: [
    {id: 1,  name: "Vertical 1",    description: "A gauche"},
    {id: 2,  name: "Diamant",       description: "A gauche"},
    {id: 3,  name: "Proue",         description: "A gauche"},
    {id: 4,  name: "Ventre 1",      description: "A gauche"},
    {id: 5,  name: "Ventre 2",      description: "A gauche"},
    {id: 6,  name: "Grand dévers",  description: "A gauche"},
    {id: 7,  name: "Nez",           description: "Devant l'entrée"},
    {id: 8,  name: "Dévers",        description: "Devant l'entrée"},
    {id: 9,  name: "Réta 1",        description: "Devant l'entrée"},
    {id: 10, name: "Dalle",         description: "A droite"},
    {id: 11, name: "Vertical 2",    description: "A droite"},
    {id: 12, name: "Petit dévers",  description: "A droite"},
    {id: 13, name: "Réta 2",        description: "A droite"},
    {id: 14, name: "Coup de sabre", description: "A droite"},
    {id: 15, name: "Grotte",        description: "A droite sous l'escalier"},
    {id: 16, name: "Tunnel",        description: "Au fond de la salle"},
  ],
};
